config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
                       omniauth_callbacks: "omniauth_callbacks",
                       passwords: "users/passwords",
                       registrations: "users/registrations",

                     }
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :messages, only: [:create]
  resources :rooms, only: %i(create show index)
  resources :players
  resources :teams
  resources :positions
  resources :microposts
  resources :follow_members, only: [:create, :destroy]

  devise_scope :user do
    root :to => "devise/sessions#new"
  end
end

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items %>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %> mb-0" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-5 bg-dark">
  <div class=twitter-share>
  <%= link_to "http://twitter.com/share?url=#{request.url}/&text=LET'SVOLEYBALLでバレーボール友達とつながろう！/&hashtags=バレーボール" do%>
    <i class="fab fa-twitter"></i> <span>Let's Share</span>
  <%end%>
  </div>
  <div>
    <p class="m-0 text-center text-white"> &copy;LET'S VOLLEY BALL since 2020</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <%= link_to "LET'S VOLLEY BALL", users_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExample03">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'アカウント編集', edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'プレイヤー検索', "/players/" , class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'チーム検索', "/teams/" , class: 'nav-link' %>
          </li>
      　<% else %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_micropost_form.erb
<%= form_for(@micropost) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "タイムラインを投稿しよう！" %>
  </div>
  <%= f.submit "投稿する", class: "btn btn-primary" %>
<% end %>

app/views/shared/_player_card.html.erb
<% @players.each do |player| %>
<div class="index_content col-lg-4 col-md-6 col-sm-6 mb-4">
  <div class="card h-100 ">
    <%if player.user.image.attached? %>
    <%= image_tag player.user.image.variant(combine_options:{gravity: :center, resize:"440x330^"}), class:"card-img-top",alt:"Card image cap" %>
    <% else %>
       <img class="card-img-top" src="http://placehold.it/700x400.ping?text=LET'S VOLLEY BALL">
    <% end %>
    <div class="card-body">
      <h4 class="card-title"><%= link_to "#{player.user.nickname}", user_path(player.user.id)%>( <small><%= player.prefecture%></small>)<small><%= player.gender %></small></h4><hr>
      <h5 class="card-subtitle" >希望ポジション</h5>
        <small class="position-name"><%= player.positions.pluck(:display_name).join(", ") %></small><hr>
      <h5 class="card-subtitle" >練習参加可能日(<%= player.available_day%>)</h5><hr>
        <p class="card-text"><%= player.comment%></p>
    </div>
      <div class="card-footer">
        <small class="text-muted"><%= link_to "詳しく見る", user_path(player.user.id)%></small>
      </div>
  </div>
</div>
<%end%>

app/views/shared/_side_menu.html.erb
<div class="home_content_sidemenu">
<ul>
  <li>
    <%= link_to users_path, method: :get do %><i class="fa fa-home"></i>  ホーム<% end %>
  </li>
  <hr>
  <li>
    <%= link_to rooms_path, method: :get do%><i class="fas fa-envelope"></i>  メッセージ<% end %>
  </li>
  <hr>
  <li>
      <%= link_to user_path(current_user.id), method: :get do %><i class="fas fa-user-alt"></i>  プロフィール<% end %>
  </li>
   <hr>
  <li>
    <%= link_to microposts_path, method: :get do %><i class="fas fa-comment-dots"></i>  タイムライン<% end %>
  </li>
   <hr>
</ul>

<% if current_user.team.present? %>
   <div class="info-tag">
      <%= link_to "マイチーム情報を編集する", edit_team_path(current_user.team)%>
    </div>
  <% else %>
    <div class="info-tag">
      <%= link_to "チーム情報の登録はこちらから", "/teams/new"%>
    </div>
<%end%>
<% if current_user.player.present? %>
   <div class="info-tag">
      <%= link_to "マイプレイヤー情報を編集する", edit_player_path(current_user.player)%>
    </div>
  <% else %>
    <div class="info-tag">
      <%= link_to "プレイヤー情報の登録はこちらから", "/players/new"%>
    </div>
<%end%>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_team_card.html.erb
<% @teams.each do |team| %>
<div class="index_content col-lg-4 col-md-6 col-sm-6 mb-4">
  <div class="card h-100">
    <%if team.user.image.attached? %>
      <%= image_tag  team.user.image.variant(resize:"200x200^")%>
    <% else %>
       <img class="card-img-top" src="http://placehold.it/700x400?text=LET'S VOLLEY BALL">
    <% end %>
    <div class="card-body">
      <h4 class="card-title"><%= link_to "#{team.name}", user_path(team.user.id)%>( <small><%= team.prefecture%></small>)<hr></h4>
      <h5 class="card-subtitle" >募集ポジション</h5>
        <small class="position-name bg-primary"><%= team.positions.pluck(:display_name).join(", ") %></small><hr>
      <h5 class="card-subtitle" ><small><%= team.available_day%>練習参加できる<%= team.gender %>性を募集しています！</small></h5><hr>
        <p class="card-text"><%= team.comment%></p>
    </div>
      <div class="card-footer">
        <small class="text-muted"><%= link_to "詳しく見る", user_path(team.user.id)%></small>
      </div>
  </div>
</div>
<%end%>