config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
                       omniauth_callbacks: "omniauth_callbacks",
                       passwords: "users/passwords",
                       registrations: "users/registrations",

                     }
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :messages, only: [:create]
  resources :rooms, only: %i(create show index)
  resources :players
  resources :teams
  resources :positions
  resources :microposts
  resources :follow_members, only: [:create, :destroy]

  devise_scope :user do
    root :to => "devise/sessions#new"
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "LET'S VolleyBall", '#', id: "logo" %>
            <nav>
                <% if user_signed_in? %>
                    <%= link_to 'アカウント情報の変更', edit_user_registration_path %>
                    <%= link_to 'プレイヤー情報登録', new_player_path%>
                    <%= link_to 'チーム情報登録', new_team_path%>
                    <% if @player%>
                        <%= link_to 'プレイヤー検索', players_path(@player)%>
                    <% end %>
                    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
                <% else %>
                    <%= link_to '今すぐ登録', new_user_registration_path %>
                    <%= link_to 'ログイン', new_user_session_path %>
                <% end %>
            </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>| LET'S VOLLEY BALL</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
    <meta charset="UTF-8">

    <% twitter_card = get_twitter_card_info() %>
      <meta name="twitter:card" content=<%= twitter_card[:card] %> />
      <meta name="twitter:site" content=<%= twitter_card[:site] %> />
      <meta property="og:url" content=<%= twitter_card[:url] %> />
      <meta property="og:title" content=<%= twitter_card[:title] %> />
      <meta property="og:description" content=<%= twitter_card[:description] %> />
      <meta property="og:image" content=<%= twitter_card[:image] %> />
      <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="wrap">
    <%= render "shared/header" %>
    <div class="container_field">
      <%= render "shared/flash_messages" %>
      <div class="row">   
        <%= yield %>  
      </div>
    </div>
    <%= render "shared/footer" %>
    </div>
  </body>
</html>